### ISSUE TITLE
schema has to define

### ISSUE THREAD

**Issue by MohammedNasheer** [Mani-Bala/spring-batch#2]
batch:
    job:
      enabled: false   # by default is true then it'll lunch job's whenever application starts
    jdbc:
      schema: org/springframework/batch/core/schema-postgresql.sql

im using this one but still batch tables aren't generating what could be the reason bro ? @Mani-Bala

**Comment by manibg** [comment]
It has to create tables on your database. However, if the batch schema table is still not created automatically, there are a few things you can check,

- Verify database access
- Check dependencies and versions
----------------
Manually create the schema: If the automatic schema initialization does not work, Locate the org/springframework/batch/core/schema-postgresql.sql file in the Spring Batch library
